version: "3.6"

services:
  lk:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - ".env"
    ports:
      - "8079:5173"
    networks:
      default:
        aliases:
          - build-and-roll-network


networks:
  default:
    name: build-and-roll-network
    external: true